[package]
name = "bisbeebee"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
async-std = "1.10"
libc = "0.2"
base64 = "0.22"
rand = "0.8.5"
md-5 = "0.10.6"

